theme: minima
title: "Architect's Palette", author: "Laszlo Andrasi, AIA", and description:"Personal site of Laszlo Andrasi, intended to be used to share interesting developments in Architecture, along with personal content sharing."
