theme: minima
title: "Architect's Palette"
author: "Laszlo Andrasi, AIA"
description: "Personal site of Laszlo Andrasi, intended to share interesting developments in Architecture, along with personal content."
